# Generated by Django 3.0.3 on 2021-03-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
